"""baseline schema

Revision ID: c1d2a9006895
Revises: 
Create Date: 2026-07-01 19:45:24.973232
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1d2a9006895'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('password_hash', sa.String(length=220), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('employee_code', sa.String(length=10), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_table('catalog_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('parent_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_segments_kind'), 'catalog_segments', ['kind'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_code', sa.String(length=20), nullable=False),
    sa.Column('minimum_stock', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('current_stock', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_item_type'), 'inventory_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_inventory_items_sku'), 'inventory_items', ['sku'], unique=True)
    op.create_table('production_processes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('product_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('raw_material_item_id', sa.UUID(), nullable=True),
    sa.Column('raw_material_quantity_per_unit', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('raw_material_unit_code', sa.String(length=20), nullable=True),
    sa.Column('waste_limit_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('process_name', sa.String(length=180), nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('raw_material_item_id', sa.UUID(), nullable=False),
    sa.Column('raw_material_quantity_per_unit', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('raw_material_unit_code', sa.String(length=20), nullable=False),
    sa.Column('total_required_material', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('waste_limit_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('expected_finished_weight', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('actual_finished_weight', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('waste_weight', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('waste_percent', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('production_code', sa.String(length=30), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('started_by_user_id', sa.UUID(), nullable=True),
    sa.Column('materials_approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('received_by_user_id', sa.UUID(), nullable=True),
    sa.Column('rejected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('materials_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_runs_process_id'), 'production_runs', ['process_id'], unique=False)
    op.create_index(op.f('ix_production_runs_production_code'), 'production_runs', ['production_code'], unique=True)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_code', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('reason', sa.String(length=240), nullable=False),
    sa.Column('reference_type', sa.String(length=80), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('lot_code', sa.String(length=30), nullable=True),
    sa.Column('source_file_name', sa.String(length=240), nullable=True),
    sa.Column('source_file_mime', sa.String(length=120), nullable=True),
    sa.Column('source_file_content', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_item_id'), 'inventory_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_lot_code'), 'inventory_movements', ['lot_code'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_table('production_process_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase_name', sa.String(length=120), nullable=True),
    sa.Column('stage_type', sa.String(length=40), nullable=False),
    sa.Column('quality_check', sa.Text(), nullable=True),
    sa.Column('rework_action', sa.Text(), nullable=True),
    sa.Column('rework_target_order', sa.Integer(), nullable=True),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_weighing', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['production_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_run_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_stage_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=180), nullable=False),
    sa.Column('phase_name', sa.String(length=120), nullable=True),
    sa.Column('stage_type', sa.String(length=40), nullable=False),
    sa.Column('quality_check', sa.Text(), nullable=True),
    sa.Column('rework_action', sa.Text(), nullable=True),
    sa.Column('rework_target_order', sa.Integer(), nullable=True),
    sa.Column('stage_code', sa.String(length=40), nullable=True),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_weighing', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_finish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_by_user_id', sa.UUID(), nullable=True),
    sa.Column('initial_weight', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('final_weight', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['production_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_run_stages_run_id'), 'production_run_stages', ['run_id'], unique=False)
    op.create_table('production_process_stage_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['production_process_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_process_stage_ingredients_stage_id'), 'production_process_stage_ingredients', ['stage_id'], unique=False)
    op.create_table('production_run_stage_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('run_stage_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('weight_based', sa.Boolean(), nullable=False),
    sa.Column('final_weight', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('returned_to_order', sa.Integer(), nullable=True),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_stage_id'], ['production_run_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_run_stage_decisions_run_id'), 'production_run_stage_decisions', ['run_id'], unique=False)
    op.create_index(op.f('ix_production_run_stage_decisions_run_stage_id'), 'production_run_stage_decisions', ['run_stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_run_stage_decisions_run_stage_id'), table_name='production_run_stage_decisions')
    op.drop_index(op.f('ix_production_run_stage_decisions_run_id'), table_name='production_run_stage_decisions')
    op.drop_table('production_run_stage_decisions')
    op.drop_index(op.f('ix_production_process_stage_ingredients_stage_id'), table_name='production_process_stage_ingredients')
    op.drop_table('production_process_stage_ingredients')
    op.drop_index(op.f('ix_production_run_stages_run_id'), table_name='production_run_stages')
    op.drop_table('production_run_stages')
    op.drop_table('production_process_stages')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_lot_code'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_item_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_production_runs_production_code'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_process_id'), table_name='production_runs')
    op.drop_table('production_runs')
    op.drop_table('production_processes')
    op.drop_index(op.f('ix_inventory_items_sku'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_type'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_catalog_segments_kind'), table_name='catalog_segments')
    op.drop_table('catalog_segments')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
